### ISSUE TITLE
SCEditor does not properly work on WolfCMS v0.8.2

### ISSUE THREAD

**Issue by anto** [svanlaere/sceditor#1]
I cloned the master branch, copy that into wolf/plugins directory and enabled that.

However, it does not work when I tried to use it to edit any pages. Every time I switch the Filter into SCEditor, it does not do anything. It turned out that my browser get 404 on the request for **wolf/plugins/sceditor/scripts/init.js**, as that file does not actually exist.

I can switch to Markdown or Textile filters but my browser still get 404 on the request for **wolf/plugins/sceditor/scripts/init.js** every time I save the page after changing the filter. But I guess since that init.js file is not relevant to Markdown and Textile filters, the functionality of those filters are not affected. So it does not actually matter whether I disable SCEditor plugin or not, those filters still work. The different is that, when I disable SCEditor plugin there is no request for **wolf/plugins/sceditor/scripts/init.js**.

The init.js is actually shown to be located on the index.php of SCEditor plugin when I grep it as below.

```
index.php:        '/wolf/plugins/sceditor/scripts/init.js' => 'plugin/sceditor/sc_init',
index.php:        Plugin::$javascripts[] = $config_path.'scripts/init.js';
```

**Comment by svanlaere** [comment]
Just updated the repo it should resolve the problem you where having.

**Comment by anto** [comment]
Thanks Samuel.

I can confirm that your [commit abe58b1604](https://github.com/svanlaere/sceditor/commit/abe58b1604acafa2f5c0fbbe4a58cf5d06639fe0) fixes the issue.

So I am closing this ticket.

Cheers,

Anto
